name: PR Landmine

on:
  pull_request:
    types: 
      - opened
      - edited
      - reopened
      - synchronize
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed

jobs:
  landmine:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: PR Landmine
      uses: tylermurry/github-pr-landmine@v1
      with:
        token: ${{ github.token }}
        test-command: ./scripts/bin/test.sh

