name: "Main-Verify Merge PR"

on: 
  pull_request:
    types: [opened, reopened, synchronize]
    branches: 
      - main

jobs:
  # Only allow `release-*` or `patch-*` branches to merge to `main`
  verify-main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: "Verify 'main' PR are from 'release-*' or 'patch-*' branch"
      run: ./scripts/workflows/branch-match.sh
      env: 
        BRANCH: ${{ github.head_ref }}
        REGEXP: (release-[0-9]+.[0-9]+|patch-[0-9]+.[0-9]+.[0-9]+)

    - name: "Verify PR Title matches `release` or `patch` "
      uses: deepakputhraya/action-pr-title@master
      with:
        regex: '-[0-9]+.[0-9]+(.[0-9]+)?'
        allowed_prefixes:  release,patch

    - name: "Verify BATS Tests Pass"
      run: 'scripts/bin/test.sh'

    - name: "Lint with Shellcheck"
      run: 'scripts/bin/lint.sh'